### ISSUE TITLE
Mountable not implemented for actix_files::Files even when actix-files feature is enabled

### ISSUE THREAD

**Issue by TheDutchMC** [paperclip-rs/paperclip#365]
Hi there,

When using paperclip `0.6.1` with the `actix_files` feature and `actix_files` version `0.5`, the `Mountable` trait from `paperclip` is not implemented for `actix_files::Files`, making it unusable. I think it should be implemented when the `actix-files` feature is enabled, but unfortunately it is not.

Here's the relevant compiler error:
```
error[E0277]: the trait bound `Files: Mountable` is not satisfied
  --> src/main.rs:75:22
   |
75 |               .service(Files::new("", "./")
   |  ______________-------_^
   | |              |
   | |              required by a bound introduced by this call
76 | |                 .prefer_utf8(true)
77 | |                 .show_files_listing()))
   | |_____________________________________^ the trait `Mountable` is not implemented for `Files`
```

Relevant parts of `Cargo.toml`:
```toml
[dependencies]
actix-web = "3.3.2"
actix-files = "0.5"

[dependencies.paperclip]
version = "0.6.1"
features = ["actix", "actix-files"]
```
Thanks.
