### ISSUE TITLE
[request] Add other data_types for integers like u8 and u16

### ISSUE THREAD

**Issue by RaulTrombin** [paperclip-rs/paperclip#516]
https://github.com/paperclip-rs/paperclip/blob/master/core/src/v2/models.rs#L67

**Comment by RaulTrombin** [comment]
From API v2 spec seens thtat types other thant i32 and i64 doesn't exist.
Maybe we can define the minimum and maximum fields for each different integer types:
https://swagger.io/specification/v2/

```
type: array
items:
  type: integer
  minimum: 0
  maximum: 63
```
